name: ci
on: [ push, pull_request ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php_version: "8.0"
            drupal_version: "9"
            composer_boundary: "lowest"
          - php_version: "8.0"
            drupal_version: "9"
            composer_boundary: "highest"
          - php_version: "8.1"
            drupal_version: "10"
            composer_boundary: "lowest"
          - php_version: "8.1"
            drupal_version: "10"
            composer_boundary: "highest"
    env:
      PHP_VERSION: ${{ matrix.php_version }}
      DRUPAL_VERSION: ${{ matrix.drupal_version }}
      DOCKER_USER_ID: "1001"
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: docker-compose up -d
        run: docker-compose up -d
      - name: composer self-update
        run: docker-compose exec -T web composer self-update
      - name: composer require
        run: docker-compose exec -u ${DOCKER_USER_ID} -T web composer require --no-interaction --dev --no-update drupal/core:^${DRUPAL_VERSION} drupal/core-composer-scaffold:^${DRUPAL_VERSION}
      - name: composer update --prefer-lowest
        if: ${{ matrix.composer_boundary == 'lowest' }}
        run: docker-compose exec -T web composer update --prefer-lowest --ansi
      - name: composer install
        if: ${{ matrix.composer_boundary == 'highest' }}
        run: docker-compose exec -T web composer install --ansi
      - name: phpcs
        run: docker-compose exec -T web vendor/bin/phpcs
      - name: phpunit
        run: docker-compose exec -T web vendor/bin/phpunit
